#!/usr/bin/bash
# Get the test html for mocked testing video id = FtutLA63Cp8.

cur=$(basename $(pwd))

if [ $cur != 'tests' ]
then
    echo 'This script must be run from within the `tests/` sub-directory.'
    exit -1
fi

curl 'https://www.youtube.com/watch?v=FtutLA63Cp8' -o 'data/raw_video.html'
